CREATE DATABASE LMS;

USE LMS;

-- Create Authors Table
CREATE TABLE AUT01 (
    T01F01 INT COMMENT "AUTHOR ID" PRIMARY KEY,
    T01F02 VARCHAR(30) COMMENT "AUTHOR NAME" NOT NULL
);

-- Create Books Table
CREATE TABLE BOO01 (
    O01F01 INT COMMENT "BOOK ID" PRIMARY KEY AUTO_INCREMENT,
    O01F02 VARCHAR(50) COMMENT "BOOK TITLE" NOT NULL,
    O01F03 INT COMMENT "AUTHOR ID" NOT NULL,
    O01F04 varchar(20) COMMENT "GENRE" DEFAULT NULL,
    FOREIGN KEY (O01F03) REFERENCES AUT01(T01F01)
);

-- Create Users Table
CREATE TABLE USE01 (
    E01F01 INT COMMENT "USER ID" PRIMARY KEY AUTO_INCREMENT,
    E01F02 VARCHAR(20) COMMENT "USERNAME" UNIQUE NOT NULL,
    E01F03 VARCHAR(16) COMMENT "PASSWORD" NOT NULL,
    E01F04 VARCHAR(16) COMMENT "Hashed PASSWORD" NOT NULL,
    E01F05 BOOL COMMENT "isActive" NOT NULL #used for soft delete
    
);

-- Create BorrowedBooks Table
CREATE TABLE BOO02 (
    O02F01 INT COMMENT "BORROW ID" PRIMARY KEY AUTO_INCREMENT,
    O02F02 INT COMMENT "USER ID" NOT NULL,
    O02F03 INT COMMENT "BOOK ID" NOT NULL,
    O02F04 DATE COMMENT "BORROW DATE" NOT NULL,
    O02F05 DATE COMMENT "RETURN DATE" NOT NULL,
    FOREIGN KEY (O02F02) REFERENCES USE01(E01F01),
    FOREIGN KEY (O02F03) REFERENCES BOO01(O01F01)
);

-- Create Transactions Table
CREATE TABLE TRA01 (
    A01F01 INT COMMENT "TRANSACTION ID" PRIMARY KEY AUTO_INCREMENT,
    A01F02 INT COMMENT "USER ID" NOT NULL,
    A01F03 VARCHAR(1) COMMENT "TRANSACTION TYPE" NOT NULL,
    A01F04 DATE COMMENT "TRANSACTION DATE",
    FOREIGN KEY (A01F02) REFERENCES USE01(E01F01)
);
